---

- name: Installation Playbook for AWX Server in Ansible Training at Wavestone.
  hosts: gcp_category_awx
  become: yes

  tasks:
    - include_vars: vars.yml

    - name: Install Git.
      apt:
        name: git
        state: latest

    - name: Install Make.
      apt:
        name: make
        state: latest

    - name: Install k3s.
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /k3s

    - name: Validate - Install k3s.
      shell: touch /k3s
      args:
        creates: /k3s

    - name: Create directory for AWX Operator repo.
      file:
        path: /awx
        state: directory

    - name: Clone AWX Operator repo.
      git:
        repo: https://github.com/ansible/awx-operator.git
        dest: /awx
        single_branch: yes
        version: "{{ awxOperatorVersion }}"

    - name: Start AWX Operator.
      make:
        target: deploy
        chdir: /awx

    - name: Create directory for AWX k3s config.
      file:
        path: /awx-config
        state: directory

    - name: Copy AWX k3s config.
      copy:
        src: /k3s/awx.yml
        dest: /awx-config/awx.yml

    - name: Start AWX.
      shell: kubectl apply -n awx -f awx.yml
      args:
        chdir: /awx-config
        creates: /awx-started

    - name: Validate - Start AWX.
      shell: touch /awx-started
      args:
        creates: /awx-started
