---

- name: Installation Playbook for AWX Server in Ansible Training at Wavestone.
  hosts: gcp_category_awx
  become: yes

  tasks:
    - include_vars: vars.yml

    - name: Install Make.
      apt:
        name: make
        state: latest

    - name: Install Git.
      apt:
        name: git
        state: latest

    - name: Install k3s.
      shell: curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
      args:
        creates: /k3s

    - name: Validate - Install k3s.
      command: touch /k3s
      args:
        creates: /k3s

    - name: Create directory for AWX Operator repo.
      file:
        path: /awx-operator
        state: directory

    - name: Clone AWX Operator repo.
      git:
        repo: https://github.com/ansible/awx-operator.git
        dest: /awx-operator
        single_branch: yes
        version: "{{ awxOperatorVersion }}"

    - name: Creates directory for AWX Kube config.
      file:
        path: /awx
        state: directory

    - name: Copy AWX Kube config 1/2.
      copy:
        src: "{{ path }}/k3s/kustomization.yml"
        dest: /awx/kustomization.yml
        owner: ansible
        group: ansible
        mode: "770"

    - name: Copy AWX Kube config 2/2.
      copy:
        src: "{{ path }}/k3s/awx.yml"
        dest: /awx/awx.yml
        owner: ansible
        group: ansible
        mode: "770"

    - name: Start AWX Operator.
      make:
        target: deploy
        chdir: /awx-operator
      environment:
        NAMESPACE: awx

    - name: Start AWX.
      command: kubectl apply -n awx -k .
      args:
        chdir: /awx
