---

- name: Check Playbook if AWX installation is running.
  hosts: gcp_category_awx
  become: yes

  tasks:
    - name: Check AWX running.
      shell: kubectl get pods -A
      register: awxCheck

    - name: Debug AWX running.
      debug:
        msg: "{{ awxCheck.stdout }}"
