---

- name: Installation Playbook for AWX Server in Ansible Training at Wavestone.
  hosts: gcp_category_awx
  become: yes

  tasks:
    - include_vars: vars.yml

    - name: Install Git.
      apt:
        name: git
        state: latest

    - name: Install Make.
      apt:
        name: make
        state: latest

    - name: Install k3s.
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /k3s

    - name: Validate - Install k3s.
      shell: touch /k3s
      args:
        creates: /k3s

    - name: Create directory for AWX Operator repo.
      file:
        path: /awx
        state: directory

    - name: Check if repo already cloned.
      stat:
        path: /awx/awx-demo.yml
      register: awxRepoPresent

    - name: Clone AWX Operator repo.
      git:
        repo: https://github.com/ansible/awx-operator.git
        dest: /awx
        single_branch: yes
        version: "{{ awxOperatorVersion }}"
      when: not awxRepoPresent.stat.exists

    - name: Copy AWX k3s config 1/3.
      copy:
        src: "{{ path }}/k3s/kustomization.yml"
        dest: /awx/kustomization.yml

    - name: Copy AWX k3s config 2/3.
      copy:
        src: "{{ path }}/k3s/awx-patch.yml"
        dest: /awx/awx-patch.yml

    - name: Copy AWX k3s config 3/3.
      copy:
        src: "{{ path }}/k3s/awx-deploy.yml"
        dest: /awx/awx-deploy.yml

    - name: Start AWX Operator.
      shell: kubectl apply -k .
      args:
        chdir: /awx

    - name: Start AWX.
      shell: kubectl apply -n awx -f awx-deploy.yml
      args:
        chdir: /awx
