---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx-operator-controller-manager
  namespace: awx
spec:
  template:
    spec:
      containers:
        - name: awx-manager
          image: quay.io/ansible/awx-operator:{awx-operator-version}
          resources:
            requests:
              memory: "0"
              cpu: "0"
            limits:
              memory: "2Gi"
              cpu: "1000m"
