---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-deploy
spec:
  service_type: nodeport
  nodeport_port: 30180
  web_resource_requirements:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: 2000m
      memory: 4Gi
  task_resource_requirements:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: 1000m
      memory: 2Gi
  ee_resource_requirements:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: 1000m
      memory: 2Gi